version: '2'
services:
  api:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/src
      - ./docker-config/api.conf:/etc/nginx/conf.d/api.conf
  php:
    image: todolist_php
    volumes:
      - .:/src
  db_mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: todolist
      MYSQL_PASSWORD: secret
