api:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - .:/src
    - ./docker-config/api.conf:/etc/nginx/conf.d/api.conf
  links:
    - php
    - db
php:
  image: php:7.4-fpm
  volumes:
    - .:/src
  links:
    - db
db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  ports:
    - 33060:3306
  environment:
    MYSQL_ROOT_PASSWORD: 123456
